---
- hosts: aws_rds
  connection: local
  tasks:
    - name: Install pip requirements
      pip:
        requirements: /runner/config/pip-requirements.txt
        state: present
    - import_tasks: ./playbooks/setup.yaml
      vars:
        application_name: "kratos"
    - import_tasks: ./playbooks/setup.yaml
      vars:
        application_name: "hydra"
