name: Build & Deploy Applications

on:
  workflow_call:
    inputs:
      force-build:
        type: boolean
        description: "Force build"
        required: true
      force-deploy:
        type: boolean
        description: "Force deploy"
        required: true
  workflow_dispatch:
    inputs:
      force-build:
        description: "Force build"
        required: true
      force-deploy:
        description: "Force deploy"
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  kratos:
    name: Kratos
    uses: "./.github/workflows/application.yaml"
    with:
      application-name: kratos
      force-build: ${{ inputs.force-build }}
      force-deploy: ${{ inputs.force-deploy }}
