name: Build & Deploy Applications

on:
  workflow_dispatch:
    inputs:
      force-build:
        type: boolean
        description: "Force build"
        required: false
      force-deploy:
        type: boolean
        description: "Force deploy"
        required: false
      image-tag:
        type: string
        description: "Image Tag to deploy"
        required: false
        default: "latest"
  workflow_call:
    inputs:
      force-build:
        type: boolean
        description: "Force build"
        required: true
      force-deploy:
        type: boolean
        description: "Force deploy"
        required: true
      image-tag:
        type: string
        description: "Image Tag to deploy"
        required: false
        default: "latest"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  kratos:
    name: Kratos
    uses: "./.github/workflows/application_run.yaml"
    with:
      application-name: kratos
      force-build: ${{ fromJson(inputs.force-build || false) }}
      force-deploy: ${{ fromJson(inputs.force-deploy || false) }}
      image-tag: ${{ inputs.image-tag }}
