name: Build & Deploy Applications

on:
  workflow_call:
    inputs:
      force-build:
        type: string
        description: "Force build"
        required: false
        default: "false"
      force-deploy:
        type: string
        description: "Force deploy"
        required: false
        default: "false"
  workflow_dispatch:
    inputs:
      force-build:
        description: "Force build"
        required: false
        default: "false"
      force-deploy:
        description: "Force deploy"
        required: false
        default: "false"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  kratos:
    name: Kratos
    uses: "./.github/workflows/application.yaml"
    with:
      application-name: kratos
      force-build: ${{ github.event.inputs.force-build == 'true' }}
      force-deploy: ${{ github.event.inputs.force-deploy == 'true' }}
