name: Application

on:
  workflow_call:
    inputs:
      force-build:
        type: boolean
        description: "Force Build"
        required: false
        default: false
      force-deploy:
        type: boolean
        description: "Force Deploy"
        required: false
        default: false
      application-name:
        type: string
        description: "Application Name"
        required: true

  workflow_dispatch:
    inputs:
      force-build:
        description: "Force Build"
        required: false
        default: "false"
      force-deploy:
        description: "Force Deploy"
        required: false
        default: "false"
      application-name:
        description: "Application Name"
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build:
    name: Build Application
    uses: ./.github/workflows/application_build.yaml
    with:
      working-directory: applications/${{ inputs.application-name }}
      application-name: ${{ inputs.application-name }}
      aws-role: ${{ vars.AWS_ROLE }}
      aws-region: ${{ vars.AWS_REGION }}
      force-build: ${{ inputs.force-build }}
  deploy:
    name: Deploy Application
    uses: ./.github/workflows/application_deploy.yaml
    needs: build
    if: github.event_name == 'push' || inputs.force-deploy
    with:
      working-directory: applications/${{ inputs.application-name }}
      application-name: ${{ inputs.application-name }}
      aws-role: ${{ vars.AWS_ROLE }}
      aws-region: ${{ vars.AWS_REGION }}
      force-deploy: ${{ inputs.force-deploy }}
