name: Build & Deploy Database Modifications

on:
  workflow_dispatch:
    inputs:
      force-build:
        type: boolean
        description: "Force provisioner to build"
        required: true
      force-run:
        type: boolean
        description: "Force provisioner to run"
        required: true
      image-tag:
        type: string
        description: "Image tag to use"
        required: true
        default: "latest"

  workflow_call:
    inputs:
      force-build:
        type: boolean
        description: "Force provisioner to build"
        required: true
        default: false
      force-run:
        type: boolean
        description: "Force provisioner to run"
        required: true
        default: false
      image-tag:
        type: string
        description: "Image tag to use"
        required: true
        default: "latest"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  provisioner:
    name: Provisioner
    uses: "./.github/workflows/database_provisioner.yaml"
    with:
      force-build: ${{ fromJson(inputs.force-build || false) }}
      force-run: ${{ fromJson(inputs.force-run || false) }}
      image-tag: ${{ inputs.image-tag }}
