name: Infrastructure

on:
  workflow_call:
    secrets:
      TERRAFORM_CLOUD_TOKEN:
        description: "Terraform Cloud Token"
        required: true
    inputs:
      force-apply:
        type: boolean
        description: "Force apply"
        required: true
      force-plan:
        type: boolean
        description: "Force plan"
        required: true
  workflow_dispatch:
    inputs:
      force-apply:
        description: "Force apply"
        required: true
      force-plan:
        description: "Force plan"
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  network:
    name: Network
    uses: ./.github/workflows/infra_terraform.yaml
    with:
      working-directory: infra/network
      aws-role: ${{ vars.AWS_ROLE }}
      aws-region: ${{ vars.AWS_REGION }}
      terraform-cloud-organization: ${{ vars.TERRAFORM_CLOUD_ORGANIZATION }}
      force-apply: ${{ inputs.force-apply }}
      force-plan: ${{ inputs.force-plan }}
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
  ecr:
    name: ECR
    uses: ./.github/workflows/infra_terraform.yaml
    with:
      working-directory: infra/ecr
      aws-role: ${{ vars.AWS_ROLE }}
      aws-region: ${{ vars.AWS_REGION }}
      terraform-cloud-organization: ${{ vars.TERRAFORM_CLOUD_ORGANIZATION }}
      force-apply: ${{ inputs.force-apply }}
      force-plan: ${{ inputs.force-plan }}
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
  database:
    name: Database
    uses: ./.github/workflows/infra_terraform.yaml
    needs:
      - network
    with:
      working-directory: infra/database
      aws-role: ${{ vars.AWS_ROLE }}
      aws-region: ${{ vars.AWS_REGION }}
      terraform-cloud-organization: ${{ vars.TERRAFORM_CLOUD_ORGANIZATION }}
      force-apply: ${{ inputs.force-apply }}
      force-plan: ${{ inputs.force-plan }}
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
  ecs:
    name: ECS
    uses: ./.github/workflows/infra_terraform.yaml
    needs:
      - network
    with:
      working-directory: infra/ecs
      aws-role: ${{ vars.AWS_ROLE }}
      aws-region: ${{ vars.AWS_REGION }}
      terraform-cloud-organization: ${{ vars.TERRAFORM_CLOUD_ORGANIZATION }}
      force-apply: ${{ inputs.force-apply }}
      force-plan: ${{ inputs.force-plan }}
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
  kratos:
    name: "Application: Kratos"
    uses: ./.github/workflows/infra_terraform.yaml
    needs:
      - network
      - ecs
      - database
    with:
      working-directory: infra/applications/kratos
      aws-role: ${{ vars.AWS_ROLE }}
      aws-region: ${{ vars.AWS_REGION }}
      terraform-cloud-organization: ${{ vars.TERRAFORM_CLOUD_ORGANIZATION }}
      force-apply: ${{ inputs.force-apply }}
      force-plan: ${{ inputs.force-plan }}
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
