name: Infrastructure

on:
  workflow_call:
    inputs:
      force-apply:
        type: boolean
        description: "Force apply"
        required: true
      force-plan:
        type: boolean
        description: "Force plan"
        required: true
  workflow_dispatch:
    inputs:
      force-apply:
        type: boolean
        description: "Force apply"
        required: false
        default: false
      force-plan:
        type: boolean
        description: "Force plan"
        required: false
        default: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  network:
    name: Network
    uses: ./.github/workflows/infra_terraform.yaml
    with:
      working-directory: infra/network
      force-apply: ${{ inputs.force-apply == 'true' }}
      force-plan: ${{ inputs.force-plan == 'true' }}
  ecr:
    name: ECR
    uses: ./.github/workflows/infra_terraform.yaml
    with:
      working-directory: infra/ecr
      force-apply: ${{ inputs.force-apply == 'true' }}
      force-plan: ${{ inputs.force-plan == 'true' }}
  database:
    name: Database
    uses: ./.github/workflows/infra_terraform.yaml
    needs:
      - network
    with:
      working-directory: infra/database
      force-apply: ${{ inputs.force-apply == 'true' }}
      force-plan: ${{ inputs.force-plan == 'true' }}
  ecs:
    name: ECS
    uses: ./.github/workflows/infra_terraform.yaml
    needs:
      - network
    with:
      working-directory: infra/ecs
      force-apply: ${{ inputs.force-apply == 'true' }}
      force-plan: ${{ inputs.force-plan == 'true' }}
  kratos:
    name: "Application: Kratos"
    uses: ./.github/workflows/infra_terraform.yaml
    needs:
      - network
      - ecs
      - database
    with:
      working-directory: infra/applications/kratos
      force-apply: ${{ inputs.force-apply == 'true' }}
      force-plan: ${{ inputs.force-plan == 'true' }}
