name: Infrastructure

on:
  workflow_call:
    secrets:
      terraform-cloud-token:
        description: "Terraform Cloud Token"
        required: true
    inputs:
      force-apply:
        type: boolean
        description: "Force apply"
        required: false
        default: false
  workflow_dispatch:
    inputs:
      force-apply:
        description: "Force apply"
        required: false
        default: "false"
      force-run:
        description: "Force run"
        required: false
        default: "false"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  network:
    name: Network
    uses: ./.github/workflows/infra_terraform.yaml
    with:
      working-directory: infra/network
      aws-role: ${{ vars.AWS_ROLE }}
      aws-region: ${{ vars.AWS_REGION }}
      terraform-cloud-organization: ${{ vars.TERRAFORM_CLOUD_ORGANIZATION }}
      force-apply: ${{ github.event.inputs.force-apply == 'true' }}
      force-run: ${{ github.event.inputs.force-run == 'true' }}
    secrets:
      terraform-cloud-token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
  ecr:
    name: ECR
    uses: ./.github/workflows/infra_terraform.yaml
    with:
      working-directory: infra/ecr
      aws-role: ${{ vars.AWS_ROLE }}
      aws-region: ${{ vars.AWS_REGION }}
      terraform-cloud-organization: ${{ vars.TERRAFORM_CLOUD_ORGANIZATION }}
      force-apply: ${{ github.event.inputs.force-apply == 'true' }}
      force-run: ${{ github.event.inputs.force-run == 'true' }}
    secrets:
      terraform-cloud-token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
  database:
    name: Database
    uses: ./.github/workflows/infra_terraform.yaml
    needs:
      - network
    with:
      working-directory: infra/database
      aws-role: ${{ vars.AWS_ROLE }}
      aws-region: ${{ vars.AWS_REGION }}
      terraform-cloud-organization: ${{ vars.TERRAFORM_CLOUD_ORGANIZATION }}
      force-apply: ${{ github.event.inputs.force-apply == 'true' }}
      force-run: ${{ github.event.inputs.force-run == 'true' }}
    secrets:
      terraform-cloud-token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
  ecs:
    name: ECS
    uses: ./.github/workflows/infra_terraform.yaml
    needs:
      - network
    with:
      working-directory: infra/ecs
      aws-role: ${{ vars.AWS_ROLE }}
      aws-region: ${{ vars.AWS_REGION }}
      terraform-cloud-organization: ${{ vars.TERRAFORM_CLOUD_ORGANIZATION }}
      force-apply: ${{ github.event.inputs.force-apply == 'true' }}
      force-run: ${{ github.event.inputs.force-run == 'true' }}
    secrets:
      terraform-cloud-token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
  kratos:
    name: "Application: Kratos"
    uses: ./.github/workflows/infra_terraform.yaml
    needs:
      - network
      - ecs
      - database
    with:
      working-directory: infra/applications/kratos
      aws-role: ${{ vars.AWS_ROLE }}
      aws-region: ${{ vars.AWS_REGION }}
      terraform-cloud-organization: ${{ vars.TERRAFORM_CLOUD_ORGANIZATION }}
      force-apply: ${{ github.event.inputs.force-apply == 'true' }}
      force-run: ${{ github.event.inputs.force-run == 'true' }}
    secrets:
      terraform-cloud-token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
