name: Infrastructure

on:
  workflow_call:
    inputs:
      force-apply:
        type: boolean
        description: "Force apply"
        required: true
      force-plan:
        type: boolean
        description: "Force plan"
        required: true
    secrets:
      TERRAFORM_CLOUD_TOKEN:
        description: "Terraform Cloud Token"
        required: true
  workflow_dispatch:
    inputs:
      force-apply:
        type: boolean
        description: "Force apply"
        required: false
      force-plan:
        type: boolean
        description: "Force plan"
        required: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  network:
    name: Network
    uses: ./.github/workflows/infra_terraform.yaml
    with:
      working-directory: infra/network
      force-apply: ${{ fromJson(inputs.force-apply) }}
      force-plan: ${{ fromJson(inputs.force-plan) }}
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

  ecr:
    name: ECR
    uses: ./.github/workflows/infra_terraform.yaml
    with:
      working-directory: infra/ecr
      force-apply: ${{ github.event.inputs.force-apply == 'true' }}
      force-plan: ${{ github.event.inputs.force-plan == 'true' }}
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

  database:
    name: Database
    uses: ./.github/workflows/infra_terraform.yaml
    needs:
      - network
    with:
      working-directory: infra/database
      force-apply: ${{ github.event.inputs.force-apply == 'true' }}
      force-plan: ${{ github.event.inputs.force-plan == 'true' }}
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

  ecs:
    name: ECS
    uses: ./.github/workflows/infra_terraform.yaml
    needs:
      - network
    with:
      working-directory: infra/ecs
      force-apply: ${{ github.event.inputs.force-apply == 'true' }}
      force-plan: ${{ github.event.inputs.force-plan == 'true' }}
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

  kratos:
    name: Kratos
    uses: ./.github/workflows/infra_terraform.yaml
    needs:
      - network
      - ecs
      - ecr
      - database
    with:
      working-directory: infra/applications/kratos
      force-apply: ${{ github.event.inputs.force-apply == 'true' }}
      force-plan: ${{ github.event.inputs.force-plan == 'true' }}
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
