name: Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/**"
  pull_request:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  network:
    uses: ./.github/workflows/terraform.yaml
    with:
      working-directory: infra/network
      aws-role: ${{ vars.AWS_ROLE }}
      aws-region: ${{ vars.AWS_REGION }}
      terraform-cloud-organization: ${{ vars.TERRAFORM_CLOUD_ORGANIZATION }}
    secrets:
      terraform-cloud-token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
