name: Main workflow

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "infra/**/*.tf"
      - "applications/**"

  pull_request:
    branches:
      - main
    paths:
      - "infra/**/*.tf"
      - "applications/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  run-infra:
    name: Run Infrastructure
    uses: "./.github/workflows/infra_main.yaml"
    with:
      force-apply: ${{ (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_name == 'main')) }}
      force-plan: ${{ (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_name == 'main')) }}
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

  run-applications:
    name: Run Applications
    needs: run-infra
    uses: "./.github/workflows/application_main.yaml"
    with:
      force-build: ${{ (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_name == 'main')) }}
      force-deploy: ${{ (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_name == 'main')) }}
