name: Main workflow

on:
  workflow_dispatch:
    inputs:
      force-apply:
        type: boolean
        description: "Force apply terraform"
        required: false
        default: false
      force-plan:
        type: boolean
        description: "Force plan terraform"
        required: false
        default: false
      force-build:
        type: boolean
        description: "Force build docker image"
        required: false
        default: false
      force-deploy:
        type: boolean
        description: "Force deploy docker image"
        required: false
        default: false
      force-modifications:
        type: boolean
        description: "Force database modifications"
        required: false
        default: false

  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "infra/**/*.tf"
      - "applications/**"
      - "database/**"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "infra/**/*.tf"
      - "applications/**"
      - "database/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  run-infra:
    name: Run Infrastructure
    uses: "./.github/workflows/infra_main.yaml"
    with:
      force-apply: ${{ (inputs.force-apply == 'true') }}
      force-plan: ${{ (inputs.force-plan == 'true') }}
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

  run-database-modifications:
    name: Run Database Modifications
    needs: run-infra
    uses: "./.github/workflows/database_main.yaml"
    with:
      force: ${{ (inputs.force-modifications == 'true') }}

  run-applications:
    name: Run Applications
    needs:
      - run-infra
      - run-database-modifications
    uses: "./.github/workflows/application_main.yaml"
    with:
      force-build: ${{ (inputs.force-build == 'true') }}
      force-deploy: ${{ (inputs.force-deploy == 'true') }}
