name: Main workflow

on:
  workflow_dispatch:
    inputs:
      force-apply:
        type: boolean
        description: "Force apply terraform"
        required: false
      force-plan:
        type: boolean
        description: "Force plan terraform"
        required: false
      force-build:
        type: boolean
        description: "Force build application images"
        required: false
      force-deploy:
        type: boolean
        description: "Force deploy application images"
        required: false
      force-db-build:
        type: boolean
        description: "Force build database images"
        required: false
      force-db-deploy:
        type: boolean
        description: "Force deploy database images"
        required: false

  push:
    branches:
      - main
    paths:
      - "infra/**/*.tf"
      - "applications/**"
      - "database/**"

  pull_request:
    branches:
      - main
    paths:
      - "infra/**/*.tf"
      - "applications/**"
      - "database/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  run-infra:
    name: Infra
    uses: "./.github/workflows/infra_main.yaml"
    with:
      force-apply: ${{ fromJson(inputs.force-apply) }}
      force-plan: ${{ fromJson(inputs.force-plan) }}
    secrets:
      TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

  run-database-modifications:
    name: Database
    needs: run-infra
    uses: "./.github/workflows/database_main.yaml"
    with:
      force-build: ${{ (github.event.inputs.force-db-build == 'true') }}
      force-run: ${{ (github.event.inputs.force-db-deploy == 'true') }}
      image-tag: "latest"

  run-applications:
    name: Apps
    needs:
      - run-infra
      - run-database-modifications
    uses: "./.github/workflows/application_main.yaml"
    with:
      force-build: ${{ (github.event.inputs.force-build == 'true') }}
      force-deploy: ${{ (github.event.inputs.force-deploy == 'true') }}
      image-tag: "latest"
